# Discord Custom Status
status:
  language: "en" # ISO 639 language code
  emoji: "💬" # Unicode emoji or custom Discord emoji
  update_interval: 10.0 # Seconds (Do not set below 4 seconds, 10-30 recommended)
  filter: on # Naughty words filter (on/off)
  censor_mode: "first_last_visible" # Can be "full", "first_last_visible" or "first_visible"

# Input Settings
recording:
  device_index: NULL # Set to null to use default mic, otherwise 0-N

# Logging
logging:
  json_indent: 2 # Can be null or int

# ******* WARNING ******************************************************************
# Please, dont fill the values below unless youre a developer, use .env file instead
# **********************************************************************************

# Environment Variables
# * If not specified here, will try to load from a .env file in the same directory *
# * Note:  Variables in .env file have to start with a "PY_DVS_" prefix by default *
env:
  DISCORD_TOKEN: ""

# Discord API
api:
  url:
    base: "https://discord.com/api/v9/"
    settings: "users/@me/settings"
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
  limits:
    max_custom_status_length: 128
    presence_update_rate_limit: 4 # Seconds
