# Discord Custom Status
status:
  language: "en" # FIXME Uncomplete feature, look into #11 on github
  filter: on
  update_interval: 10.0 # Seconds (Do not set below 4 seconds, 10-30 recommended)

# Environment Variables
# (If not specified here, will try to load from a .env file in the same directory)
env:
  DISCORD_TOKEN: ""

# Discord API
api:
  url:
    base: "https://discord.com/api/v9/"
    settings: "users/@me/settings"
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
  limits:
    max_custom_status_length: 128
    presence_update_rate_limit: 4 # Max 1 update per <- seconds

